# Generated by Django 5.2.7 on 2025-10-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(blank=True, default='', max_length=200)),
                ('nap', models.CharField(blank=True, default='', max_length=120)),
                ('activity', models.CharField(blank=True, default='', max_length=200)),
                ('behavior', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_by', models.CharField(blank=True, default='', max_length=120)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='children.child')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
