# Generated by Django 5.2.7 on 2025-10-18 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=None)),
                (
                    "meal",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Repas"
                    ),
                ),
                (
                    "nap",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Sieste"
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Comportement",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                ("has_mobile_app", models.BooleanField(default=False)),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Soumis par",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="children.child",
                        db_index=True,
                        verbose_name="Enfant",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport journalier",
                "verbose_name_plural": "Rapports journaliers",
                "ordering": ["-created_at"],
            },
        ),
    ]
