# Generated by Django 5.2.7 on 2025-10-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
    ]
