# Generated by Django 5.2.7 on 2025-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_dailyreport_unique_together"),
    ]

    operations = [
        # has_mobile_app is already included in 0001_initial migration
    ]
