# Generated by Django 5.2.7 on 2025-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_dailyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='has_mobile_app',
            field=models.BooleanField(default=False),
        ),
    ]
