# Generated by Django 5.2.7 on 2025-10-23 19:14

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailyreport_has_mobile_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.report_media_path, verbose_name='Photo/Vidéo'),
        ),
    ]
