# Generated by Django 5.2.7 on 2025-10-23 19:27

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0005_dailyreport_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='media',
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reports.models.report_media_path, verbose_name='Photo/Vidéo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='reports.dailyreport', verbose_name='Rapport associé')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Fichier média du rapport',
                'verbose_name_plural': 'Fichiers médias des rapports',
            },
        ),
    ]
