# Generated by Django 5.2.7 on 2025-10-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('teacher_name', models.CharField(blank=True, default='', max_length=120)),
                ('assistant_name', models.CharField(blank=True, default='', max_length=120)),
                ('age_range', models.CharField(blank=True, default='', max_length=40)),
                ('room', models.CharField(blank=True, default='', max_length=40)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('parent_name', models.CharField(max_length=120)),
                ('avatar', models.URLField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='children.classroom')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
