# Generated by Django 5.2.7 on 2025-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
        migrations.AddField(
            model_name='child',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
