# Generated by Django 5.2.7 on 2025-10-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_remove_child_age_child_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='avatar',
        ),
    ]
