# Generated by Django 5.2.7 on 2025-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_remove_child_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
