# Generated by Django 5.2.7 on 2025-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_child_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='child',
            name='conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='child',
            name='doctor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='child',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='medication',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='child',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
