# Generated by Django 5.2.7 on 2025-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_child_allergies_child_conditions_child_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='has_mobile_app',
            field=models.BooleanField(default=False),
        ),
    ]
