# Generated by Django 5.2.7 on 2025-10-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_child_has_mobile_app'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du club')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('instructor_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Encadrant')),
                ('schedule', models.CharField(blank=True, default='', max_length=120, verbose_name='Horaires')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='child',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='children.club'),
        ),
    ]
