# Generated by Django 5.2.7 on 2025-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_club_child_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='club',
        ),
        migrations.AddField(
            model_name='child',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='children', to='children.club', verbose_name='Clubs'),
        ),
    ]
