# Generated by Django 5.2.7 on 2025-10-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_remove_child_club_child_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='responsible_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='child',
            name='responsible_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
