# Generated by Django 5.2.7 on 2025-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0009_child_responsible_name_child_responsible_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='teacher_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
