# Generated by Django 5.2.7 on 2025-10-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_child_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='teacher_name',
        ),
    ]
