# Generated by Django 5.2.7 on 2025-11-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='time',
        ),
    ]
